Horsebean Summary Table:

In [9]:
import pandas as pd
pd.DataFrame({"minimum weight (lb)": ["108"], "mean (lb)": ["160.2"], "maximum weight (lb)": ["227"], "range (lb)": ["119"]})

  minimum weight (lb) mean (lb) maximum weight (lb) range (lb)
0                 108     160.2                 227        119

Linseed Summary Table:

In [10]:
import pandas as pd
pd.DataFrame({"minimum weight (lb)": ["141"], "mean (lb)": ["218.75"], "maximum weight (lb)": ["309"], "range (lb)": ["168"]})

  minimum weight (lb) mean (lb) maximum weight (lb) range (lb)
0                 141    218.75                 309        168

Soybean Summary Table:

In [12]:
import pandas as pd
pd.DataFrame({"minimum weight (lb)": ["158"], "mean (lb)": ["246.4285714"], "maximum weight (lb)": ["329"], "range (lb)": ["171"]})

  minimum weight (lb)    mean (lb) maximum weight (lb) range (lb)
0                 158  246.4285714                 329        171

Sunflower Summary Table:

In [13]:
import pandas as pd
pd.DataFrame({"minimum weight (lb)": ["226"], "mean (lb)": ["328.9166667"], "maximum weight (lb)": ["423"], "range (lb)": ["197"]})

  minimum weight (lb)    mean (lb) maximum weight (lb) range (lb)
0                 226  328.9166667                 423        197

Meatmeal Summary Table:

In [14]:
import pandas as pd
pd.DataFrame({"minimum weight (lb)": ["153"], "mean (lb)": ["276.9090909"], "maximum weight (lb)": ["380"], "range (lb)": ["227"]})

  minimum weight (lb)    mean (lb) maximum weight (lb) range (lb)
0                 153  276.9090909                 380        227

Casein Summary Table:

In [15]:
import pandas as pd
pd.DataFrame({"minimum weight (lb)": ["216"], "mean (lb)": ["323.5833333"], "maximum weight (lb)": ["404"], "range (lb)": ["188"]})

  minimum weight (lb)    mean (lb) maximum weight (lb) range (lb)
0                 216  323.5833333                 404        188

The best feed to use to maximize chicken weight is sunflower because it yields the highest average weight. While its range is one of the largest (197 lb), which means the weight of an individual chicken is hard to precisely predict, the minimum weight for this feed is the highest of all (226 lb). This means that even if the individual weights vary a lot, even the lowest likely weight would still be desirable. Contrast this with horsebean, which possesses a much tighter range (119 lb), but its maximum weight is a mere 227 lb: Nearly equal to the minimum weight of sunflower-fed chicks. A risk-averse strategy that specifically seeks to minimize range alone, and thus chooses horsebean, would poorly serve the goal of consistently high chick weights. Choosing sunflower would actually be much more risk-averse if risk-averse is defined as a high minimum weight rather than as a tight range.